import type { Metadata } from "next";
import "./globals.css";
import { getCurrentUser } from "@/lib/auth";
import { AbilityProvider } from "@/lib/AbilityProvider";
import { QueryProvider } from "@/lib/QueryProvider";

export const metadata: Metadata = {
  title: "Admin Dashboard",
  description: "Generated by create next app",
};

export default async function RootLayout({children} : {children : React.ReactNode}) {

  const user = await getCurrentUser()

  return (
    <html lang="en">
      <body>
        <QueryProvider>
          <AbilityProvider role={user.role}>
            {children}
          </AbilityProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
